AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - lib/docker/connection.rb
    - lib/excon/middlewares/hijack.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Lint/EmptyFile:
  Exclude:
    - spec/factories.rb
