#!/bin/bash

args=""

function run_bundle_inside_container {
  docker run -v `pwd`:/usr/src/app $args \
    --rm \
    -p 4040:9292 \
    kunday/gondola:latest \
    $@
}

if [ -z "$1" ]
then
  args="-it"
  run_bundle_inside_container bash
else
  echo "bundle $@"
  run_bundle_inside_container bundle "$@"
fi
exit $?
