development:
  adapter: mysql2
  host: db
  username: root
  password: password
  reconnect: true
  database: pantaloon_development
test:
  adapter: mysql2
  host: db
  username: root
  password: password
  reconnect: true
  database: pantaloon_test
production:
  adapter: mysql2
  host: db
  username: root
  password: password
  reconnect: true
  database: pantaloon_production
